import logo from './logo.svg';
import './App.css';
import FormComponent from './FormComponent';
import { useReducer,useState } from 'react';
import { reducer } from './reducer';
import Context from './context';


function App() {

  let [goodsArr,setGoodsArr] = useState([ {
    id :1,
    product_name: "Kişi köynəyi",
    product_description: "Mavi rəngdə, 100% pamuk",
    product_price: 50,
  },
  {
    id :2,
    product_name: "Qadın bluzası",
    product_description: "Dəri detallı, qara rəngdə",
    product_price: 60,
  },
  { id :3,
    product_name: "Kişi pantolonu",
    product_description: "Qəhvəyi rəng, kənar cebi",
    product_price: 75,
  },
  { id :4,
    product_name: "Qadın eteyi",
    product_description: "Qırmızı rəng, mini",
    product_price: 40,
  },
  { id :5,
    product_name: "Kişi dəsmalı",
    product_description: "Nəqşdar dizayn",
    product_price: 20,
  },
  { id :6,
    product_name: "Qadın çantası",
    product_description: "Əlgötürən, dəri",
    product_price: 90,
  },
  { id :7,
    product_name: "Kişi botları",
    product_description: "Qış üçün, suya davamlı",
    product_price: 120,
  },
  { id :8,
    product_name: "Qadın ayaqqabıları",
    product_description: "Yüksək tapan, lacivərt",
    product_price: 85,
  },
  { id :9,
    product_name: "Kişi papağı",
    product_description: "Qara rəngdə, dəri",
    product_price: 45,
  },
  { id :10,
    product_name: "Qadın şalvarı",
    product_description: "Göy rəngdə, kaşmir",
    product_price: 70,
  },
  { id :11,
    product_name: "Kişi palto",
    product_description: "Süət dəri, qara rəngdə",
    product_price: 250,
  },
  { id :12,
    product_name: "Qadın jaketi",
    product_description: "Uzun, qaşqır",
    product_price: 200,
  },
  { id :13,
    product_name: "Kişi kəməri",
    product_description: "Dəri, metal tokalı",
    product_price: 40,
  },
  { id :14,
    product_name: "Qadın badlonu",
    product_description: "Retro stil, qızıl rəngdə",
    product_price: 180,
  },
  { id :15,
    product_name: "Kişi şortu",
    product_description: "Spor stil, elastik",
    product_price: 60,
  },
  { id :16,
    product_name: "Qadın maykası",
    product_description: "Boyalı nəqş, pamuklu",
    product_price: 45,
  },
  { id :17,
    product_name: "Kişi saatı",
    product_description: "Qara rəngdə, analog",
    product_price: 150,
  },
  { id :18,
    product_name: "Qadın bəzək",
    product_description: "Qızıl, komplekt",
    product_price: 220,
  },
  { id :19,
    product_name: "Kişi atkısı",
    product_description: "Xəzəl rəng, uzun",
    product_price: 35,
  },
  { id :20,
    product_name: "Qadın bantı",
    product_description: "Metal detallı, elastik",
    product_price: 50,
  },

  { id :21,
    product_name: "Kişi kostyumu",
    product_description: "İki parçalı, qara rəngdə",
    product_price: 320,
  },
  { id :22,
    product_name: "Qadın kombinezonu",
    product_description: "Yaz üçün, açıq rəng",
    product_price: 150,
  },
  { id :23,
    product_name: "Kişi sviteri",
    product_description: "Düz rəng, yüngül",
    product_price: 70,
  },
  { id :24,
    product_name: "Qadın ziyafət geyimi",
    product_description: "Düzənşən, yaz üçün",
    product_price: 95,
  },
  { id :25,
    product_name: "Kişi sport formaları",
    product_description: "Spandex, idman üçün",
    product_price: 55,
  },
  { id :26,
    product_name: "Qadın bikini",
    product_description: "Tropik nəqş, elastik",
    product_price: 45,
  },
  { id :27,
    product_name: "Kişi çantası",
    product_description: "Dizayner, əsas bölməsi",
    product_price: 100,
  },
  { id :28,
    product_name: "Qadın ətri",
    product_description: "Gül ətri, uzunömürlü",
    product_price: 80,
  },
  { id :29,
    product_name: "Kişi şalı",
    product_description: "Səliqəli, çoxrəngli",
    product_price: 25,
  },
  { id :30,
    product_name: "Qadın sutyeni",
    product_description: "Destəklənmiş, rahat",
    product_price: 65,
  },
])

  let [state,dispatch] = useReducer(reducer,goodsArr);

  let [obj, setObj] = useState({ product_name: "", product_description: "", product_price: null,
  });

  return (
    <Context.Provider value={{state:state,dispatch:dispatch,obj:obj,setObj:setObj}}>
      <div className="App">
      {/* <Modal/> */}
      <FormComponent/>
      </div>

    </Context.Provider>
    
  );
}

export default App;
